### ISSUE TITLE
Source Code is desktop short cut not code

### ISSUE THREAD

**Issue by rnwolf** [brucemcpherson/GoingGas#1]
Hi Bruce

I was hoping to access the code examples in your book. In the GoingGas repo I notice links to the code and not the code.
For example
https://github.com/brucemcpherson/GoingGas/blob/master/htmlservice/gas/source/desktop.ini
[.ShellClassInfo]
InfoTip=This folder is shared online.
IconFile=C:\Program Files (x86)\Google\Drive\googledrivesync.exe
IconIndex=16

Is it possible to get the code rather than links?  I don't run googledrivesync.exe.

**Comment by brucemcpherson** [comment]
Hi

The code is also available generally under the source directory of each project..

For example

https://github.com/brucemcpherson/GoingGas/tree/master/addons/gas/source

Holds the all the source code for the links held in 

https://github.com/brucemcpherson/GoingGas/tree/master/addons/gas/scripts

You should also be able to see the source in the apps script editor by opening the url link held in the equivalent script file

https://github.com/brucemcpherson/GoingGas/blob/master/addons/gas/scripts/mapsExample.gscript

It's not necessary to run drive sync. You can just pull the whole repo with git, or if you prefer copy the source from git hub as required. Google apps files are not like others .. They simply hold links to cloud based content. That's why I also published a copy of the source code in GitHub.

Not all directories have things in them yet as I plan to add additional examples not in the book over time. All the examples in the book reference which example holds its code.

You'll find details of how the GitHub repo is organized in the book appendix.

If you any further trouble accessing, let me know

Regards
Bruce

**Comment by rnwolf** [comment]
Thanks I've downloaded master branch. Will start reading you book now.
